### PR TITLE
MUST NOT include classes, traits and objects inside package objects

### PR DESCRIPTION
**Pull request by nermin**
Adding a rule about what goes inside package objects.

### CODE REVIEW

**Comment by lukasz-golebiewski** [comment]
:+1:

**Comment by HolyHaddock** [comment]
This is interesting. I'd been putting everything in package objects on the basis that it was the one kind of thing that everything could go into. Why bother with packages at all when they're like packages-but-more-restricted, and I gain no benefit in, say, useful discipline that's enforced from the restriction.

How does it confuse the compiler? Google had little to say on the subject, is there a source for this?

**Comment by lukasz-golebiewski** [comment]
What about this: http://www.scala-lang.org/docu/files/packageobjects/packageobjects.html?

**Comment by lukasz-golebiewski** [comment]
And this: http://stackoverflow.com/questions/17270003/why-are-classes-inside-scala-package-objects-dispreferred

**Comment by HolyHaddock** [comment]
The relevant bits seem to be that redefining other symbols (classes, methods or vals) won't work in a package object, objects in package objects can't have a main method, -Xlint will flag warnings, and that package objects are closed?

**Pull request merged**
